# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$basic_pkgs = <<SCRIPT
  yum update -y
  yum install vim -y 
SCRIPT

Vagrant.configure("2") do |config|
 config.vm.box = 'centos/7'
 config.vm.provision "shell" , inline: $basic_pkgs 
 config.vm.hostname = "puppetserver1.venkat.com"
 config.vm.network "private_network", ip: "192.168.56.190"


config.vm.provider :virtualbox do |vb|
 vb.customize ["modifyvm", :id, "--memory",4096]
 vb.customize ["modifyvm", :id, "--cpus", 1]
end 

end
